In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [84]:
df= pd.read_csv("cleaned_datayt.csv")

In [85]:
df

Unnamed: 0     video_id trending_date  \
0               0  2kyS6SvSYSE    2017-11-14   
1               1  1ZAPwfrtAFY    2017-11-14   
2               2  5qpjK5DgCt4    2017-11-14   
3               3  puqaWrEC7tY    2017-11-14   
4               4  d380meD0W0M    2017-11-14   
...           ...          ...           ...   
40944       40944  BZt0qjTWNhw    2018-06-14   
40945       40945  1h7KV2sjUWY    2018-06-14   
40946       40946  D6Oy4LfoqsU    2018-06-14   
40947       40947  oV0zkMe1K8s    2018-06-14   
40948       40948  ooyjaVdt-jA    2018-06-14   

                                                   title  \
0                     WE WANT TO TALK ABOUT OUR MARRIAGE   
1      The Trump Presidency: Last Week Tonight with J...   
2      Racist Superman | Rudy Mancuso, King Bach & Le...   
3                       Nickelback Lyrics: Real or Fake?   
4                               I Dare You: GOING BALD!?   
...                                                  ...   
40944                       The Cat Who Caught the Laser   
40945                         True Facts : Ant Mutualism   
40946  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...   
40947                How Black Panther Should Have Ended   
40948  Official Call of Duty®: Black Ops 4 — Multipla...   

                  channel_title  category_id               publish_time  \
0                  CaseyNeistat           22  2017-11-13 17:13:01+00:00   
1               LastWeekTonight           24  2017-11-13 07:30:00+00:00   
2                  Rudy Mancuso           23  2017-11-12 19:05:24+00:00   
3         Good Mythical Morning           24  2017-11-13 11:00:04+00:00   
4                      nigahiga           24  2017-11-12 18:01:41+00:00   
...                         ...          ...                        ...   
40944             AaronsAnimals           15  2018-05-18 13:00:04+00:00   
40945                  zefrank1           22  2018-05-18 01:00:06+00:00   
40946                Brad Mondo           24  2018-05-18 17:34:22+00:00   
40947  How It Should Have Ended            1  2018-05-17 17:00:04+00:00   
40948              Call of Duty           20  2018-05-17 17:09:38+00:00   

          views   likes  dislikes  comment_count  comments_disabled  \
0        748374   57527      2966          15954              False   
1       2418783   97185      6146          12703              False   
2       3191434  146033      5339           8181              False   
3        343168   10172       666           2146              False   
4       2095731  132235      1989          17518              False   
...         ...     ...       ...            ...                ...   
40944   1685609   38160      1385           2657              False   
40945   1064798   60008       382           3936              False   
40946   1066451   48068      1032           3992              False   
40947   5660813  192957      2846          13088              False   
40948  10306119  357079    212976         144795              False   

       ratings_disabled  video_error_or_removed             Genre  
0                 False                   False    People & Blogs  
1                 False                   False     Entertainment  
2                 False                   False            Comedy  
3                 False                   False     Entertainment  
4                 False                   False     Entertainment  
...                 ...                     ...               ...  
40944             False                   False    Pets & Animals  
40945             False                   False    People & Blogs  
40946             False                   False     Entertainment  
40947             False                   False  Film & Animation  
40948             False                   False            Gaming  

[40949 rows x 15 columns]

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Unnamed: 0              40949 non-null  int64 
 1   video_id                40949 non-null  object
 2   trending_date           40949 non-null  object
 3   title                   40949 non-null  object
 4   channel_title           40949 non-null  object
 5   category_id             40949 non-null  int64 
 6   publish_time            40949 non-null  object
 7   views                   40949 non-null  int64 
 8   likes                   40949 non-null  int64 
 9   dislikes                40949 non-null  int64 
 10  comment_count           40949 non-null  int64 
 11  comments_disabled       40949 non-null  bool  
 12  ratings_disabled        40949 non-null  bool  
 13  video_error_or_removed  40949 non-null  bool  
 14  Genre                   40949 non-null  object
dtypes:

In [87]:
df = df.drop(columns=['Unnamed: 0'])

In [88]:
# Convert date columns to datetime
df['trending_date'] = pd.to_datetime(df['trending_date'])
df['publish_time'] = pd.to_datetime(df['publish_time'])

In [89]:
df.isnull().sum()

video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_time              0
views                     0
likes                     0
dislikes                  0
comment_count             0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
Genre                     0
dtype: int64

In [90]:
df = df.drop(columns=['comments_disabled', 'ratings_disabled', 'video_error_or_removed'], inplace=False)

In [91]:
df=df.drop(columns=['video_id'])


In [93]:
df['Genre'].unique()

array(['People & Blogs', 'Entertainment', 'Comedy',
       'Science & Technology', 'Film & Animation', 'News & Politics',
       'Sports', 'Music', 'Pets & Animals', 'Education', 'Howto & Style',
       'Autos & Vehicles', 'Travel & Events', 'Gaming',
       'Nonprofits & Activism', 'Shows'], dtype=object)

In [94]:
df

trending_date                                              title  \
0        2017-11-14                 WE WANT TO TALK ABOUT OUR MARRIAGE   
1        2017-11-14  The Trump Presidency: Last Week Tonight with J...   
2        2017-11-14  Racist Superman | Rudy Mancuso, King Bach & Le...   
3        2017-11-14                   Nickelback Lyrics: Real or Fake?   
4        2017-11-14                           I Dare You: GOING BALD!?   
...             ...                                                ...   
40944    2018-06-14                       The Cat Who Caught the Laser   
40945    2018-06-14                         True Facts : Ant Mutualism   
40946    2018-06-14  I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...   
40947    2018-06-14                How Black Panther Should Have Ended   
40948    2018-06-14  Official Call of Duty®: Black Ops 4 — Multipla...   

                  channel_title  category_id              publish_time  \
0                  CaseyNeistat           22 2017-11-13 17:13:01+00:00   
1               LastWeekTonight           24 2017-11-13 07:30:00+00:00   
2                  Rudy Mancuso           23 2017-11-12 19:05:24+00:00   
3         Good Mythical Morning           24 2017-11-13 11:00:04+00:00   
4                      nigahiga           24 2017-11-12 18:01:41+00:00   
...                         ...          ...                       ...   
40944             AaronsAnimals           15 2018-05-18 13:00:04+00:00   
40945                  zefrank1           22 2018-05-18 01:00:06+00:00   
40946                Brad Mondo           24 2018-05-18 17:34:22+00:00   
40947  How It Should Have Ended            1 2018-05-17 17:00:04+00:00   
40948              Call of Duty           20 2018-05-17 17:09:38+00:00   

          views   likes  dislikes  comment_count             Genre  
0        748374   57527      2966          15954    People & Blogs  
1       2418783   97185      6146          12703     Entertainment  
2       3191434  146033      5339           8181            Comedy  
3        343168   10172       666           2146     Entertainment  
4       2095731  132235      1989          17518     Entertainment  
...         ...     ...       ...            ...               ...  
40944   1685609   38160      1385           2657    Pets & Animals  
40945   1064798   60008       382           3936    People & Blogs  
40946   1066451   48068      1032           3992     Entertainment  
40947   5660813  192957      2846          13088  Film & Animation  
40948  10306119  357079    212976         144795            Gaming  

[40949 rows x 10 columns]

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [96]:
label_encoders = {}
for column in ['category_id', 'Genre']:  # Assuming 'Genre' and 'category_id' are categorical
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

In [100]:
genre_encoder = label_encoders['Genre']

# Create the mapping dictionary
encoded_genres = dict(zip(
    genre_encoder.classes_,
    genre_encoder.transform(genre_encoder.classes_)
))


In [101]:
encoded_genres

{'Autos & Vehicles': 0,
 'Comedy': 1,
 'Education': 2,
 'Entertainment': 3,
 'Film & Animation': 4,
 'Gaming': 5,
 'Howto & Style': 6,
 'Music': 7,
 'News & Politics': 8,
 'Nonprofits & Activism': 9,
 'People & Blogs': 10,
 'Pets & Animals': 11,
 'Science & Technology': 12,
 'Shows': 13,
 'Sports': 14,
 'Travel & Events': 15}

In [97]:
df['Genre'].unique()

array([10,  3,  1, 12,  4,  8, 14,  7, 11,  2,  6,  0, 15,  5,  9, 13])

In [65]:
X = df[['views', 'dislikes', 'comment_count','Genre']]
y = df['likes']

In [66]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [67]:
X_test

views  dislikes  comment_count  Genre
15632   206028       329           2951      7
40759   402418      3303           2142     10
10536  1437372      1626           2233      3
11029   417790       346           2000      3
8202    816662       468           1038      3
...        ...       ...            ...    ...
2074    506084       249           1953      6
34074   350313       576           2569      1
2799      5696         0              1     10
22972  1469234      2108          82422      3
8561    715332      1148           3435      2

[8190 rows x 4 columns]

In [68]:
# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)


In [69]:
y_pred

array([ 20937.69857885,  14927.6959699 ,  38096.42070218, ...,
         6595.23114403, 344121.53742251,  30530.23492183])

In [70]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")

Mean Squared Error: 5350539748.116079
R^2 Score: 0.8787248271432228


In [71]:
import pickle

In [73]:
with open('model.pickle', 'wb') as model_file:
    pickle.dump(model,model_file)

In [74]:
with open('model.pickle', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

In [77]:
X_test

views  dislikes  comment_count  Genre
15632   206028       329           2951      7
40759   402418      3303           2142     10
10536  1437372      1626           2233      3
11029   417790       346           2000      3
8202    816662       468           1038      3
...        ...       ...            ...    ...
2074    506084       249           1953      6
34074   350313       576           2569      1
2799      5696         0              1     10
22972  1469234      2108          82422      3
8561    715332      1148           3435      2

[8190 rows x 4 columns]

In [76]:
X = df[['views', 'dislikes', 'comment_count','Genre']]

In [78]:
loaded_model.predict([[206028,329,2951,7]])

c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([20937.69857885])